"""
=========================================================
IoT Traffic Monitoring & Anomaly Detection System
=========================================================

Module: Interactive Dashboard

Description:

Interactive dashboard developed with Streamlit for
visualizing Machine Learning evaluation results and
network anomaly detection.

The dashboard provides an overview of the complete
pipeline, including model performance, anomaly
statistics and analysed captures.

Author: Marta Parás
"""

# =========================================================
# Imports
# =========================================================

# Dashboard
import streamlit as st

# Project configuration
from src.config import (
    PROJECT_NAME,
    VISUALIZATION_DIR
)

# Dashboard utilities
from src.visualization.dashboard_utils import (
    load_model_results,
    get_detection_statistics,
    get_best_model,
    get_capture_names,
    load_capture
)

# =========================================================
# Page configuration
# =========================================================

st.set_page_config(
    page_title="IoT Traffic Monitoring",
    page_icon="🛡️",
    layout="wide"
)

# =========================================================
# Header
# =========================================================

st.title(PROJECT_NAME)

st.markdown(
    """
    Interactive dashboard for monitoring IoT traffic,
    evaluating Machine Learning models and analysing
    network anomalies.
    """
)

st.divider()

# =========================================================
# Global statistics
# =========================================================

detection_statistics = get_detection_statistics()

best_model = get_best_model()

column1, column2, column3, column4 = st.columns(4)

column1.metric(
    "Captures",
    detection_statistics["captures"]
)

column2.metric(
    "Windows",
    detection_statistics["windows"]
)

column3.metric(
    "Anomalies",
    detection_statistics["anomalies"]
)

column4.metric(
    "Best Model",
    best_model["name"]
)

st.divider()

# =========================================================
# Machine Learning evaluation
# =========================================================

st.header("Machine Learning Evaluation")

st.info(
    "The Random Forest model achieved the best overall performance and "
    "is therefore used as the primary anomaly detector."
)

model_results = load_model_results()

st.dataframe(
    model_results,
    width="stretch",
    hide_index=True
)

st.metric(
    "Best F1-Score",
    f"{best_model['f1_score']:.3f}"
)

st.divider()

# =========================================================
# Generated visualizations
# =========================================================

st.header("Project Visualizations")

image1, image2 = st.columns(2)

with image1:

    st.image(
        VISUALIZATION_DIR / "model_comparison.png",
        caption="Model Comparison",
        width="stretch"
    )

with image2:

    st.image(
        VISUALIZATION_DIR / "anomalies_by_capture.png",
        caption="Detected Anomalies by Capture",
        width="stretch"
    )

st.image(
    VISUALIZATION_DIR / "confusion_matrix.png",
    caption="Random Forest Confusion Matrix",
    width=750
)

st.divider()

# =========================================================
# Detection results
# =========================================================

st.header("Detection Results")

st.info(
    "Select any analysed capture to inspect the anomaly detection results "
    "generated by the trained Machine Learning models."
)

capture_names = get_capture_names()

selected_capture = st.selectbox(
    "Select a capture",
    capture_names
)

capture_dataframe = load_capture(selected_capture)

total_windows = len(capture_dataframe)

anomalies = int(capture_dataframe["final_prediction"].sum())

normal = total_windows - anomalies

column1, column2, column3 = st.columns(3)

column1.metric(
    "Windows",
    total_windows
)

column2.metric(
    "Normal",
    normal
)

column3.metric(
    "Anomalies",
    anomalies
)

st.dataframe(
    capture_dataframe,
    width="stretch",
    hide_index=True
)

st.divider()

# =========================================================
# Footer
# =========================================================

st.caption(
    "IoT Traffic Monitoring & Anomaly Detection System | "
    "Developed by Marta Parás"
)